#!/usr/bin/env bash

###############################################################
### Initial Variables #########################################
###############################################################

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
CLEAR='\033[0m'

###############################################################
### Help Dialog ###############################################
###############################################################

show_help() {
  echo -e "
$(printf '=%.0s' $(seq 1 $(tput cols)))
 ${GREEN}███████╗███████╗██╗  ██╗███████╗██████╗ 
 ${GREEN}██╔════╝██╔════╝██║  ██║██╔════╝██╔══██╗
 ${GREEN}███████╗███████╗███████║█████╗  ██████╔╝
 ${GREEN}╚════██║╚════██║██╔══██║██╔══╝  ██╔══██╗
 ${GREEN}███████║███████║██║  ██║███████╗██║  ██║
 ${GREEN}╚══════╝╚══════╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝${CLEAR}
$(printf '=%.0s' $(seq 1 $(tput cols)))
  Usage:${RED} $0 ${GREEN}-m mode -i inventory_file_path [-u username] [-p] [-s private_key] [-l local_file] [-r remote_file] [-c 'command']
  
  Options:
 ${RED}   -m mode                ${GREEN}Specifies the mode of operation. Options are 'run', 'script', 'ping', 'ins', 'download', 'upload', or 'man'.
 ${RED}                          ${GREEN}use 'debug' to get output of the options per server
 ${RED}                          ${GREEN}This option is required.
 ${RED} 
 ${RED}                          ${GREEN}run       =  Run a command on all the servers
 ${RED}                          ${GREEN}script    =  Like run except runs a full script you have locally. If you need to run a script on the server or from a remote location use the run mode.
 ${RED}                          ${GREEN}ping      =  Test SSH access to servers, reports the auth mechanism
 ${RED}                          ${GREEN}ins       =  Add contents of a local file to a target file on the server. Good for pushing public keys with password mode (better than ssh-copy-id)
 ${RED}                          ${GREEN}download  =  Pull contents from remote servers to the local server. Great for auditing/updating configurations. 
 ${RED}                          ${GREEN}upload    =  Push contents from local server to the remote servers. Great for uploading configurations. 
 ${RED}                          ${GREEN}man       =  Run tasks on the servers manually in sequence. (Good for when you need to authenticate using run) (Good for macros)
 ${RED}                          ${GREEN}debug     =  output what is going to run on each server. Useful when using special variables to change things dynamically
 ${RED} 
 ${RED}   -i inventory_file      ${GREEN}Path to the file containing a list of server hostnames or IP addresses.
 ${RED}                          ${GREEN}This option is required.
 ${RED} 
 ${RED}   -o options             ${GREEN}define custom ssh options
 ${RED}                          ${GREEN}just like in normal ssh you can pass -o options.
 ${RED}                          ${GREEN}by default stricthostchecking is disabled and connection timeouts are set to 8 seconds
 ${RED}                          ${GREEN}this is not limited to -o you can pass ANY ssh options to this flag
 ${RED}                          ${GREEN}If you use this option stricthostchecking and the connectiontimout options are removed, you will need to add them again
 ${RED}
 ${RED}   -p                     ${GREEN}Prompts for a password for password authentication. (THIS REQUIRES SSHPASS)
 ${RED}                          ${GREEN}If not provided, you will have to enter the password for each server that needs it.
 ${RED}                          ${GREEN}Not using this is useful when you have different passwords on different servers
 ${RED} 
 ${RED}   -l local_file          ${GREEN}Specifies the file which content to push. Optional.
 ${RED}                          ${GREEN}Default is your public key 'id_rsa.pub'.
 ${RED}                          ${GREEN}Used in script mode to define the script you want to run
 ${RED} 
 ${RED}   -r remote_file         ${GREEN}Specifies the file to push local file contents to. Optional.
 ${RED}                          ${GREEN}Default is the remote authorized keys file 'authorized_keys'.
 ${RED} 
 ${RED}   -s Private_key         ${GREEN}Specifies the identity key file to use for authentication. Optional.
 ${RED}                          ${GREEN}Default is according to your config file or just 'id_rsa'.
 ${RED} 
 ${RED}   -u username            ${GREEN}Specifies the username for the operation. Optional.
 ${RED}                          ${GREEN}Default is the current user's username.
 ${RED} 
 ${RED}   -c command             ${GREEN}The command to run when in run mode.
 ${RED}                          ${GREEN}Wrap with \"\" when there's spaces (most of the time)
 ${RED} 
  Examples:
   ${RED}$0 ${GREEN}-m run -i oldservers.txt -c 'apt update && apt upgrade -y && apt autoremove -y'                    ${CLEAR}# Update a list of servers
   ${RED}$0 ${GREEN}-m ping -i serversthatshouldbelocked.txt -u root -p | tee sshaudit.txt                             ${CLEAR}# Check what servers are not secured
   ${RED}$0 ${GREEN}-m ins -i newserver.txt -u newkid -l ~/.ssh/newuser.pub                                            ${CLEAR}# Add a new users public key to the server
   ${RED}$0 ${GREEN}-m ping -i servers.txt -u root -o '-J root@jumphost.ip' -u root                                    ${CLEAR}# Add a jumphost for pivoting from
   ${RED}$0 ${GREEN}-m ins -i service.txt -u root -l ./config.txt -d /etc/service/configuration.txt                    ${CLEAR}# set configuration file on server
   ${RED}$0 ${GREEN}-m man -i bootstrapthese.txt -u root -p                                                            ${CLEAR}# Manually perform common tasks back to back
   ${RED}$0 ${GREEN}-m ping -i servers.txt -u user -s ~/.ssh/newkey.id_rsa                                             ${CLEAR}# Check what servers have your new key
   ${RED}$0 ${GREEN}-m script -i servers.txt -u root -l ~/.local/bin/profileconfig.sh                                  ${CLEAR}# configure your shell profile on all servers
   ${RED}$0 ${GREEN}-m download -i servers.txt -u root -l ~/reports/\$date_auth.log -r /var/log/auth.log                ${CLEAR}# pull all the auth logs to investigate today's access
   ${RED}$0 ${GREEN}-m upload -i servers.txt -u root -l ~/.confs/static_ips -r /etc/networking/interfaces              ${CLEAR}# after downloading interfaces files you and update them, then upload them
   ${RED}$0 ${GREEN}-m run -i servers.txt -u root -c 'reboot'                                                          ${CLEAR}# reboot all servers
   ${RED}$0 ${GREEN}-m run -i servers.txt -u root -c 'systemctl --failed'                                              ${CLEAR}# list all failed services in your network

  PROTIPS:
  ${RED}building inventories is easy with nmap:${GREEN} nmap -n -Pn -p 22 192.168.4.0/24 -oG - | grep "open" | awk '{ print $2 }'

  ${RED}Create a Report that you can read:${CLEAR} ${GREEN}$0 -m ping -i ips.list |tee date.report${CLEAR} # This outputs the color mask for bash, make sure to cat the file to get the color output appropriately
                                                                  ${GREEN}cat date.report${CLEAR} # vim does not render ANSI escape codes without help use cat, more, less as much as you can

$(printf '=%.0s' $(seq 1 $(tput cols)))" | less
}

###############################################################
### Argument parser ###########################################
###############################################################
# Detect option collisions # TEST
declare -A SET SRC
set_opt() {
  local key=$1 val=$2 src=$3
  if [[ -v SET[$key] ]]; then
    echo "error: '$key' specified twice (first ${SRC[$key]}, then $src)"
    exit 1
  fi
  SET[$key]=$val
  SRC[$key]=$src
  printf -v "$key" '%s' "$val"
}

OPTS=$(getopt -o m:i:o:u:s:pl:r:c: -l inventory:,options:,user:,idfile:,password,localfile:,remotefile:,cmd: -- "$@") || exit 2
eval set -- "$OPTS"
while true; do
  case "$1" in
    -i|--inventory)          set_opt inventory   "$2" "$1";  shift 2;;
    -o|--options)            set_opt options     "$2" "$1";  shift 2;;
    -u|--user|--username)    set_opt username    "$2" "$1";  shift 2;;
    -s|--idfile)             set_opt idfile      "$2" "$1";  shift 2;;
    -l|--localfile)          set_opt localfile   "$2" "$1";  shift 2;;
    -r|--remotefile)         set_opt remotefile  "$2" "$1";  shift 2;;
    -c|--cmd)                set_opt cmd         "$2" "$1";  shift 2;;
    -p|--password)           set_opt password    "1"  "$1";  shift 1;;
    --) shift; break;;
  esac
done

# Set mode
mode="${1:-}"; shift

case "$mode" in
    test|ping|run|script|insert|download|upload|man) ;;
    ""|*) show_help; exit 1; ;;
esac

###############################################################
### Preflight #################################################
###############################################################

#######################
### Capabilities ######
#######################
[ -z $(command -v sshpass) ] || { sshpass=1; }

#######################
### Defaults ##########
#######################
[ -z "$username" ] && username=$USER
[ ! -z "$idfile" ] && idfilecmd=" -i ${idfile}";
[ -z "$options" ] && { optionscmd=" -o BatchMode=yes -o StrictHostKeyChecking=no -o ConnectTimeout=3"; }
[ ! -z "$options" ] && { optionscmd=" ${options} -o BatchMode=yes"; } # TODO Create batch mode toggle (this can cause dangerous breakages is why it should be dedicated)

#######################
### Early failures ####
#######################
[ -z "$mode" ] || [ -z "$inventory" ] && { show_help && exit 1; }
[ ! -f "$inventory" ] && { echo "FATAL: Selected inventory file (${inventory}) doesn't seem to exist. Check your pwd."; exit 1; }
[ ! -z "$password" ] && [ -z "$sshpass" ] && { echo "FATAL: sshpass is not available and -p was used"; exit 1; }
if [ ! -z "$idfile" ]; then # We still continue because you can defer to external configuration for auth id
  [ ! -f "$idfile" ] && { echo "FATAL: Selected private key ${idfile} doesn't seem to exist."; exit 1; }
fi
case $mode in "test"|"script"|"insert"|"download"|"upload")
    [ -z "$localfile" ] && { echo "FATAL: Local file required when in $mode mode"; exit 1; } ;;
esac
case $mode in "test"|"insert"|"download"|"upload")
    [ -z "$remotefile" ] && { echo "FATAL: Remote file required when in $mode mode"; exit 1; } ;;
esac
case $mode in "test"|"run")
    [ -z "$cmd" ] && { echo "FATAL: Command is required in run mode"; exit 1; } ;;
esac

#######################
### Inputs Required ###
#######################
[ -z "$password" ] || { read -s -p "Please enter the password for traditional authentication: " password; echo ""; }
[ "$mode" == "insert" ] || [ "$mode" == "test" ] && read -r -p "Using insert mode, Append or Override? O/A? " write
case "$write" in
  [oO]) overwrite=1 ;;
  *) ;;
esac
echo $password

#######################
### command builder ###
#######################
[ ! -z "$password" ] && { passwordcmd="sshpass -p ${password} "; passwordcmdredacted="sshpass -p REDACTED "; }

sshcmdredacted="${passwordcmdredacted}ssh $username@-------${idfilecmd}${optionscmd}"
sshcmd="${passwordcmd}ssh ${idfilecmd}${optionscmd}"

#######################
### Confirmation ######
#######################

echo ""
[[ -v $idfilecmd ]] && echo -e "Private Key: ${GREEN}$idfile${CLEAR}"

if [ "$mode" == "insert" ] || [ "$mode" == "test" ]; then
  if [ "$overwrite" == "1" ]; then
      echo -e "Write mode: ${RED}Overwrite${CLEAR}"
  else
      echo -e "Write mode: ${GREEN}Append${CLEAR}"
  fi
fi

case $mode in "test"|"script"|"insert"|"download"|"upload")
    echo -e "local file: ${GREEN}$localfile${CLEAR}" ;;
esac
case $mode in "test"|"insert"|"download"|"upload")
    echo -e "remote file: ${GREEN}$remotefile${CLEAR}" ;;
esac

echo -e "Username: ${GREEN}$username${CLEAR}"
echo -e "Servers to attempt (cat the file if you're unsure): ${GREEN}$inventory${CLEAR}"

case $mode in "test"|"run")
    echo -e "Command: ${GREEN}$cmd${CLEAR}" ;;
esac

echo -e "SSH: ${GREEN}${sshcmdredacted}${CLEAR}"

countdowntime=3
while [ $countdowntime -gt 0 ]; do
    echo -ne "${RED}Make sure to read this! $countdowntime\033[0K\r${CLEAR}"
    sleep 1
    countdowntime=$((countdowntime-1))
done

if [ ! "$mode" == "test" ]; then
  read -r -p "Are you sure you want to run this? [y/n] " confirm
  case "$confirm" in
      [yY][eE][sS]|[yY])
          ;;
      *)
          exit 1
          ;;
  esac
  echo ""
  echo "=============================================================="
else
  exit 0
fi

###############################################################
### helper functions ##########################################
###############################################################


###############################################################
### Modes #####################################################
###############################################################

#######################
### Run ###############
#######################
run() {
    #"run") run "$inventory" "$password" "$username" "$cmd" "$debug";;
    inventory=$1
    password=$2
    username=$3
    cmd=$4

    for server in $(cat $inventory); do

        ssh_output=$($sshcmd $username@${server} "${cmd}" 2>&1)
        ssh_status=$?

        if [ $ssh_status -eq 0 ]; then
            echo -e "${GREEN}SUCCESS ${server}${CLEAR}" 
            echo "--------------------------------------------------------------"
            echo "$ssh_output"
            echo "=============================================================="
        else
            echo -e "${RED}FAILED ${server}${CLEAR}" 
            echo "--------------------------------------------------------------"
            echo "$ssh_output"
            echo "=============================================================="
        fi
    done
}

#######################
### script ############
#######################
script() {
    # fail if option is missing
    if [ "$3" == 0 ]; then
        echo "FATAL: you need -l to choose a script file locally"
        exit 0
    fi

    # Fail if local file is not found
    if [ ! -f $3 ]; then
        echo "FATAL: Selected local file (${3}) doesn't seem to exist. Check your pwd."
        exit 1
    fi

    for server in `cat $1`; do

        ssh_output=$($sshcmd $5@${server} 'bash -s' < ${3} 2>&1)
        ssh_status=$?

        if [ $ssh_status -eq 0 ]; then
            echo -e "${GREEN}SUCCESS ${server}${CLEAR}" 
            echo "--------------------------------------------------------------"
            echo "$ssh_output"
            echo "=============================================================="
        else
            echo -e "${RED}FAILED ${server}${CLEAR}" 
            echo "--------------------------------------------------------------"
            echo "$ssh_output"
            echo "=============================================================="
        fi
    done
}

#######################
### ping ##############
#######################
ping() {

    inventory=$1
    password=$2
    username=$3
    for server in `cat $1`; do

        ssh_output=$($sshcmd $username@${server} -v exit 0 2>&1)
        ssh_status=$?

        if [ $ssh_status -eq 0 ]; then
            echo -e "${GREEN}SUCCESS ${server}${CLEAR}" 
            echo "--------------------------------------------------------------"
            if echo "$ssh_output" | grep -q "Server accepts key:"; then
                echo -e "${GREEN}Public key authentication${CLEAR}" 
            else
                echo -e "${YELLOW}Password Authentication${CLEAR}"
            fi
            echo "=============================================================="
        else
            echo -e "${RED}FAILED ${server}${CLEAR}" 
            echo "--------------------------------------------------------------"
            echo "$ssh_output"
            echo "=============================================================="
        fi
    done
}

#######################
### insert ############
#######################
ins() {
    # Fail if requirements are missing
    if [ "$3" == 0 ]; then
        echo "FATAL: you need -l to have content to push"
        exit 0
    fi

    if [ "$7" == 0 ]; then
        echo "FATAL: you need -r to push the content to"
        exit 0
    fi

    # Fail if local file is not found
    if [ ! -f $3 ]; then
        echo "FATAL: Selected local file (${3}) doesn't seem to exist. Check your pwd."
        exit 1
    fi

    for server in `cat $1`; do

        ssh_output=$(cat $3 |$sshcmd $5@${server} "cat >> ${7}" 2>&1)
        ssh_status=$?

        if [ $ssh_status -eq 0 ]; then
            echo -e "${GREEN}SUCCESS ${server}${CLEAR}" 
            echo "--------------------------------------------------------------"
            echo "Wrote: $3"
            echo "To: $7"
            echo "=============================================================="
        else
            echo -e "${RED}FAILED ${server}${CLEAR}" 
            echo "--------------------------------------------------------------"
            echo "$ssh_output"
            echo "=============================================================="
        fi
    done
}

#######################
### download ##########
#######################
download() {

    if [ "$3" == 0 ]; then
        echo "FATAL: you need -l to put the content somewhere"
        exit 0
    fi

    if [ "$7" == 0 ]; then
        echo "FATAL: you need -r to pull the content"
        exit 0
    fi

    for server in `cat $1`; do

        echo "" >> $3
        echo "##\$\$##| ${server} |##\$\$##" >> $3
        ssh_output=$($sshcmd $5@${server} "cat ${7}" >> ${3} 2>&1)
        ssh_status=$?

        if [ $ssh_status -eq 0 ]; then
            echo -e "${GREEN}SUCCESS ${server}${CLEAR}" 
            echo "--------------------------------------------------------------"
            echo "Wrote: $7"
            echo "To: $3"
            echo "=============================================================="
        else
            echo -e "${RED}FAILED ${server}${CLEAR}" 
            echo "--------------------------------------------------------------"
            echo "$ssh_output"
            echo "=============================================================="
        fi
    done
}

#######################
### upload ############
#######################
upload() {

    if [ "$3" == 0 ]; then
        echo "FATAL: you need -l to push the content somewhere"
        exit 0
    fi
    if [ "$7" == 0 ]; then
        echo "FATAL: you need -r to put the content somewhere"
        exit 0
    fi

    for server in `cat $1`; do

        content=$(sed -n "/^##\$\$##| ${server} |##\$\$##$/,/^##\$\$##| /{ /^##\$\$##| ${server} |##\$\$##$/d; /^##\$\$##| /d; p; }" $3 | sed '/^$/d')
        echo "# ============================ ${server} ==================================="
        ssh_output=$($sshcmd $5@${server} "echo $content > ${7}" 2>&1)
        ssh_status=$?

        if [ $ssh_status -eq 0 ]; then
            echo -e "${GREEN}SUCCESS ${server}${CLEAR}" 
            echo "--------------------------------------------------------------"
            echo "Wrote: $3"
            echo "To: $7"
            echo "=============================================================="
        else
            echo -e "${RED}FAILED ${server}${CLEAR}" 
            echo "--------------------------------------------------------------"
            echo "$ssh_output"
            echo "=============================================================="
        fi
    done
}

#######################
### manual ############
#######################
man() {
    for server in `cat $1`; do
        $sshcmd $5@${server}
    done
}

#######################
### debug #############
#######################
debug() {
    for server in `cat $1`; do
        echo "=============================================================="
        echo -e "${GREEN}debug mode - ${server}${CLEAR}"
        echo "--------------------------------------------------------------"
        echo -e "Inventory:   ${GREEN}  $1  ${CLEAR}"
        echo -e "Username:    ${GREEN}  $5  ${CLEAR}"
        echo -e "Idfile:      ${GREEN}  $4  ${CLEAR}"
        echo -e "Password:    ${GREEN}  $2  ${CLEAR}"
        echo -e "local file:  ${GREEN}  $3  ${CLEAR}"
        echo -e "remote file: ${GREEN}  $7  ${CLEAR}"
        echo -e "Command:     ${GREEN}  $6  ${CLEAR}"
    done
}

# Main logic based on mode
case $mode in
  "run") run "$inventory" "$password" "$username" "$cmd";;
  "script") script "$inventory" "$password" "$localfile" "$idfile" "$username" "$cmd" "$debug";;
  "ping") ping "$inventory" "$password" "$username";;
  "ins") ins "$inventory" "$password" "$localfile" "$idfile" "$username" "$cmd" "$remotefile";;
  "download") download "$inventory" "$password" "$localfile" "$idfile" "$username" "$cmd" "$remotefile";;
  "upload") upload "$inventory" "$password" "$localfile" "$idfile" "$username" "$cmd" "$remotefile";;
  "man") man "$inventory" "$password" "$localfile" "$idfile" "$username" "$cmd" "$debug";;
  "debug") debug "$inventory" "$password" "$localfile" "$idfile" "$username" "$cmd" "$debug";;
  *) show_help; exit 1;;
esac

